server:
  port: 8087

spring:
  application:
    name: reward-service
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/greenloop_reward_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    function:
      definition: ecoPointDonationConsumer
    stream:
      bindings:
        ecoPointDonation-int-0:
          destination: ecopoint-donation
          group: ${spring.application.name}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: 1
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

rabbitmq:
  exchangeName: greenloop.exchange
  eco-donation-queue: ecoDonationQueue
  eco-donation-routing-key: ecoDonationQueueRoutingKey

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
  instance:
    ip-address: ${REWARD_HOST:localhost}
    prefer-ip-address: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    disable-swagger-default-url: true
    urls:
      - name: Gateway (Production)
        url: http://${GATEWAY_HOST}/reward-service/v3/api-docs
      - name: Direct (Internal)
        url: http://${SERVICE_HOST}:${server.port}/v3/api-docs