server:
  port: 8084

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/greenloop_notification_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:12345}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  cloud:
    function:
      definition: userRegistrationConsumer;passwordResetConsumer
    stream:
      bindings:
        userRegistrationConsumer-in-0:
          destination: user-registration
          group: ${spring.application.name}
        passwordResetConsumer-in-0:
          destination: password-reset
          group: ${spring.application.name}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
  instance:
    ip-address: ${NOTIFICATION_HOST:localhost}
    prefer-ip-address: true


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    disable-swagger-default-url: true
    urls:
      - name: Gateway (Production)
        url: http://${GATEWAY_HOST}/notification-service/v3/api-docs
      - name: Direct (Internal)
        url: http://${SERVICE_HOST}:${server.port}/v3/api-docs



rabbitmq:
  exchangeName: greenloop.exchange
  notification-queue: notificationQueue
  notification-routing-key: notificationQueueRoutingKey