version: '3.8'

services:
  eureka-server:
    build: ./eureka
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - greenloop-network
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - greenloop-network
  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      DB_HOST: mysql
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - eureka-server
      - redis
    networks:
      - greenloop-network
  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8084:8084"
    depends_on:
      - mysql
      - eureka-server
      - redis
    networks:
      - greenloop-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - greenloop-network

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - greenloop-network

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - greenloop-network

volumes:
  mysql_data:
  rabbitmq_data:

networks:
  greenloop-network:
    driver: bridge