spring:
  application:
    name: gateway

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  security:
    jwt:
      secret: ${JWT_SECRET}

  cloud:
    gateway:
      defaultFilters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      global-cors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
  instance:
    hostname: ${GATEWAY_HOST:localhost}
    prefer-ip-address: false

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    disable-swagger-default-url: true
    urls:
      - name: User Service
        url: /user-service/v3/api-docs
      - name: Event Service
        url: /event-service/v3/api-docs
      - name: Order Service
        url: /order-service/v3/api-docs
