
spring:
  application:
    name: gateway
  data:
    redis:
      host: localhost
      port: 6379
  security:
    jwt:
      secret: bXlTZWNyZXRLZXlGb3JHcmVlbkxvb3BBdXRoU2VydmljZVNob3VsZEJlQXRMZWFzdDI1NkJpdHNMb25n

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

