spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  instance:
    hostname: ${EUREKA_HOST:eureka-server}
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
