spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/greenloop_order_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:12345}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  cloudinary:
    cloudName: ${CLOUDINARY_NAME}
    apiKey: ${CLOUDINARY_API_KEY}
    apiSecret: ${CLOUDINARY_API_SECRET}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  rabbitmq:
    host: ${RABBITMQ_HOST:35.198.237.130}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
  instance:
    ip-address: ${ORDER_HOST:localhost}
    prefer-ip-address: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    disable-swagger-default-url: true
    urls:
      - name: Gateway
        url: http://${GATEWAY_HOST}/order-service/v3/api-docs
      - name: Direct
        url: http://${SERVICE_HOST:localhost}:${server.port}/v3/api-docs

goship:
  token: ${GOSHIP_TOKEN}
  client-id: ${GOSHIP_CLIENT_ID}
  client-secret: ${GOSHIP_CLIENT_SECRET}
  access-token: ${GOSHIP_ACCESS_TOKEN}
  base-url: ${GOSHIP_BASE_URL:https://sandbox.goship.io/api/v2}

payos:
  client-id: ${PAYOS_CLIENT_ID}
  api-key: ${PAYOS_API_KEY}
  checksum-key: ${PAYOS_CHECKSUM_KEY}
  return-url-mobile: ${PAYOS_RETURN_URL_MOBILE:greenloop://payment-success}
  return-url-web: ${PAYOS_RETURN_URL:http://localhost:5173/payments/success}
  cancel-url-web: ${PAYOS_CANCEL_URL:http://localhost:5173/payments/fail}
  cancel-url-mobile: ${PAYOS_CANCEL_URL_MOBILE:greenloop://payment-failed}

greenloop:
  defaultImg: ${DEFAULT_IMAGE_URL:https://res.cloudinary.com/demo/image/upload/sample.jpg}

order:
  redis:
    pending-order-ttl: 900

rabbitmq:
  exchangeName: greenloop.exchange
  notification-routing-key: notificationQueueRoutingKey